import Head from 'next/head'
import styles from '../../styles/Home.module.css'

export default function Home() {
  return (
      <>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h1 className='font-medium leading-tight text-5xl mt-0 mb-2 text-blue-600'>Index page</h1>
        </main>
      </>
  )
}
